export { default as Htag } from "./Htag/Htag";
export { default as Button } from "./Button/Button";
export { default as P } from "./P/P";
export { default as Tag } from "./Tag/Tag";
export { default as Rating } from "./Rating/Rating";
export { default as Card } from "./Card/Card";
export { default as HhData } from "./HhData/HhData";
export { default as Divider } from "./Divider/Divider";
export { default as Advantages } from "./Advantages/Advantages";
